name: send_money_app
description: A simple Send Money Flutter application with Clean Architecture, Bloc, Dio & Interceptor.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dio: ^5.3.3
  equatable: ^2.0.5
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: any
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
